name:                factcheck
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/factcheck#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           All Rights Reserved
category:            Unclassified
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - corenlp-parser
  - text
  - containers
  - unordered-containers

executables:
  factcheck:
    source-dirs:      src
    main:             Main.hs
