name:                taikyoku-shogi
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/taikyoku-shogi#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           All Rights Reserved
category:            Unclassified
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - text
  - formatting

executables:
  taikyoku-shogi:
    source-dirs:      src
    main:             Main.hs
