name:                sms-spam
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/sms-spam#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           Kostiantyn Rybnikov
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  sms-spam:
    source-dirs:      src
    main:             Main.hs
