name:                naiveml
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/naiveml#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           All Rights Reserved
category:            Unclassified
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - newtype
  - aeson
  - hashable
  - text
  - string-class
  - unordered-containers

library:
  source-dirs:      src
  ghc-options: -Wall
  exposed-modules: NaiveML.MultinomialNaiveBayes
