name:                common-crabl
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/common-crabl#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           All Rights Reserved
category:            Unclassified
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - cld2
  - groom
  - lens
  - monoidal-containers
  - network-uri
  - pipes
  - pipes-bytestring
  - pipes-zlib
  - safe-exceptions
  - string-class
  - text
  - transformers
  - unordered-containers
  - warc

executables:
  common-crabl:
    source-dirs:      src
    main:             Main.hs
    ghc-options: -Wall -funbox-strict-fields
