name:                snowball-stem
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/snowball-stem#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           All Rights Reserved
category:            Unclassified
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - snowball
  - text

executables:
  snowball-stem:
    source-dirs:      src
    main:             Main.hs
